INSERT OR IGNORE INTO quotes (category, author, quote) VALUES
('Finance', 'Warren Buffett', 'Risk comes from not knowing what you’re doing.'),
('Finance', 'Ray Dalio', 'The biggest mistake investors make is to believe that what happened in the recent past is likely to persist.'),
('Finance', 'Benjamin Graham', 'The intelligent investor is a realist who sells to optimists and buys from pessimists.'),
('Finance', 'Charlie Munger', 'The big money is not in the buying and selling, but in the waiting.'),
('Finance', 'Peter Lynch', 'Know what you own, and know why you own it.'),
('Finance', 'John Bogle', 'The two greatest enemies of the equity fund investor are expenses and emotions.'),
('Finance', 'Paul Tudor Jones', 'Losers average losers.'),
('Finance', 'Jesse Livermore', 'Markets are never wrong, opinions often are.'),
('Finance', 'George Soros', 'It’s not whether you’re right or wrong that’s important, but how much money you make when you’re right and how much you lose when you’re wrong.'),
('Finance', 'Stanley Druckenmiller', 'I learned that nothing is foolproof. You have to be flexible.'),

('Economics', 'John Maynard Keynes', 'Markets can remain irrational longer than you can remain solvent.'),
('Economics', 'Milton Friedman', 'Inflation is always and everywhere a monetary phenomenon.'),
('Economics', 'Adam Smith', 'The real tragedy of the poor is the poverty of their aspirations.'),
('Economics', 'David Ricardo', 'The value of a commodity, therefore, depends on the relative quantity of labor which is necessary for its production.'),
('Economics', 'Joseph Schumpeter', 'Creative destruction is the essential fact about capitalism.'),
('Economics', 'Thomas Sowell', 'The first lesson of economics is scarcity: there is never enough of anything to satisfy all those who want it.'),
('Economics', 'Paul Samuelson', 'Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.'),
('Economics', 'Friedrich Hayek', 'The curious task of economics is to demonstrate to men how little they really know about what they imagine they can design.');