from __future__ import annotations

import os
from dotenv import load_dotenv

load_dotenv()


# ----------------- MSAL (AEGIS Controls) ------------------

AEGIS_MSAL_CLIENT_SECRET_VALUE = os.getenv("AEGIS_MSAL_CLIENT_SECRET_VALUE")
AEGIS_MSAL_CLIENT_SECRET_ID = os.getenv("AEGIS_MSAL_CLIENT_SECRET_ID")
AEGIS_MSAL_CLIENT_ID = os.getenv("AEGIS_MSAL_CLIENT_ID")
AEGIS_MSAL_TENANT_ID = os.getenv("AEGIS_MSAL_TENANT_ID")

AEGIS_MSAL_GRAPH_BASE = "https://graph.microsoft.com/v1.0"
AEGIS_MSAL_SCOPES = ["https://graph.microsoft.com/.default"]
AEGIS_MSAL_AUTHORITY = f"https://login.microsoftonline.com/{AEGIS_MSAL_TENANT_ID}"


AEGIS_MSAL_EMAIL_SENDER_MAIL = os.getenv("AEGIS_MSAL_EMAIL_SENDER_MAIL")
AEGIS_MSAL_EMAIL_RECIPIENT_MAIL = os.getenv("AEGIS_MSAL_EMAIL_RECIPIENT_MAIL")

AEGIS_MSAL_EMAIL_BREACH_LOG_SUBJECT = os.getenv("AEGIS_MSAL_EMAIL_BREACH_LOG_SUBJECT")
AEGIS_MSAL_EMAIL_BREACH_LOG_CONTENT = os.getenv("AEGIS_MSAL_EMAIL_BREACH_LOG_CONTENT")

AEGIS_MSAL_EMAIL_BREACH_COMM_SUBJECT = os.getenv("AEGIS_MSAL_EMAIL_BREACH_COMM_SUBJECT")
AEGIS_MSAL_EMAIL_BREACH_COMM_CONTENT = os.getenv("AEGIS_MSAL_EMAIL_BREACH_COMM_CONTENT")

