from __future__ import annotations

import os
from dotenv import load_dotenv

load_dotenv()

# ------------ LibAPI ---------------

LIBAPI_ABS_PATH = os.getenv("LIBAPI_ABS_PATH")


# ------------ AEGIS Sqlite Database ----------------

AEGIS_DATABASE_ABS_PATH = os.getenv("AEGIS_DATABASE_ABS_PATH")


# ------------ AEGIS Leverages ------------

AEGIS_LEVERAGES_ALL_FILENAME = os.getenv("AEGIS_LEVERAGES_ALL_FILENAME")
AEGIS_LEVERAGES_FUND_HV_DIR_PATH = os.getenv("AEGIS_LEVERAGES_FUND_HV_DIR_PATH")
AEGIS_LEVERAGES_FUND_WR_DIR_PATH = os.getenv("AEGIS_LEVERAGES_FUND_WR_DIR_PATH")

AEGIS_LEVERAGES_FUNDS_DIR_PATHS = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_LEVERAGES_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_LEVERAGES_FUND_WR_DIR_PATH,

}

AEGIS_LEVERAGES_UNDERL_FUND_HV_DIR_PATH = os.getenv("AEGIS_LEVERAGES_UNDERL_FUND_HV_DIR_PATH")
AEGIS_LEVERAGES_UNDERL_FUND_WR_DIR_PATH = os.getenv("AEGIS_LEVERAGES_UNDERL_FUND_WR_DIR_PATH")

AEGIS_LEVERAGES_UNDERL_FUNDS_DIR_PATHS = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_LEVERAGES_UNDERL_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_LEVERAGES_UNDERL_FUND_WR_DIR_PATH,

}

AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH = os.getenv("AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH")
AEGIS_LEVERAGES_TRADE_FUND_WR_DIR_PATH = os.getenv("AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH")

AEGIS_LEVERAGES_TRADE_FUNDS_DIR_PATHS = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_LEVERAGES_TRADE_FUND_WR_DIR_PATH,

}


# ------------ Aegis SIMM / VaR --------------

AEGIS_IM_ICE_FUND_HV_DIR_PATH = os.getenv("AEGIS_IM_ICE_FUND_HV_DIR_PATH")
AEGIS_IM_ICE_FUND_WR_DIR_PATH = os.getenv("AEGIS_IM_ICE_FUND_WR_DIR_PATH")

AEGIS_IM_ICE_FUNDS_DIR_PATH = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_IM_ICE_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_IM_ICE_FUND_WR_DIR_PATH

}

AEGIS_IM_CTPY_FUND_HV_DIR_PATH = os.getenv("AEGIS_IM_CTPY_FUND_HV_DIR_PATH")
AEGIS_IM_CTPY_FUND_WR_DIR_PATH = os.getenv("AEGIS_IM_CTPY_FUND_WR_DIR_PATH")

AEGIS_IM_CTPY_FUNDS_DIR_PATH = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_IM_CTPY_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_IM_CTPY_FUND_WR_DIR_PATH

}

AEGIS_VM_ICE_FUND_HV_DIR_PATH = os.getenv("AEGIS_VM_ICE_FUND_HV_DIR_PATH")
AEGIS_VM_ICE_FUND_WR_DIR_PATH = os.getenv("AEGIS_VM_ICE_FUND_WR_DIR_PATH")

AEGIS_VM_ICE_FUNDS_DIR_PATH = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_VM_ICE_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_VM_ICE_FUND_WR_DIR_PATH

}


AEGIS_VM_CTPY_FUND_HV_DIR_PATH = os.getenv("AEGIS_VM_CTPY_FUND_HV_DIR_PATH")
AEGIS_VM_CTPY_FUND_WR_DIR_PATH = os.getenv("AEGIS_VM_CTPY_FUND_WR_DIR_PATH")

AEGIS_VM_CTPY_FUNDS_DIR_PATH = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_VM_CTPY_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_VM_CTPY_FUND_WR_DIR_PATH

}


AEGIS_IM_ICE_FILE = os.getenv("AEGIS_IM_ICE_FILE")
AEGIS_IM_CTPY_FILE = os.getenv("AEGIS_IM_CTPY_FILE")


# ------------ Aegis NAV  --------------

AEGIS_NAV_ESTIMATE_DIR_PATH_FUND_HV = os.getenv("AEGIS_NAV_ESTIMATE_DIR_PATH_FUND_HV")
AEGIS_NAV_ESTIMATE_DIR_PATH_FUND_WR = os.getenv("AEGIS_NAV_ESTIMATE_DIR_PATH_FUND_WR")
AEGIS_NAV_ESTIMATE_FILENAME = os.getenv("AEGIS_NAV_ESTIMATE_FILENAME")

AEGIS_NAV_ESTIMATE_FUNDS_DIR_PATH = {
    
    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_NAV_ESTIMATE_DIR_PATH_FUND_HV,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_NAV_ESTIMATE_DIR_PATH_FUND_WR

}
