from __future__ import annotations

import os
from dotenv import load_dotenv

load_dotenv()

# ------------ LibAPI ---------------

LIBAPI_ABS_PATH = os.getenv("LIBAPI_ABS_PATH")


# ------------ AEGIS Sqlite Database ----------------

AEGIS_DATABASE_ABS_PATH = os.getenv("AEGIS_DATABASE_ABS_PATH")


# ------------ AEGIS Leverages ------------

AEGIS_LEVERAGES_ALL_FILENAME = os.getenv("AEGIS_LEVERAGES_ALL_FILENAME")
AEGIS_LEVERAGES_FUND_HV_DIR_PATH = os.getenv("AEGIS_LEVERAGES_FUND_HV_DIR_PATH")
AEGIS_LEVERAGES_FUND_WR_DIR_PATH = os.getenv("AEGIS_LEVERAGES_FUND_WR_DIR_PATH")

AEGIS_LEVERAGES_FUNDS_DIR_PATHS = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_LEVERAGES_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_LEVERAGES_FUND_WR_DIR_PATH,

}

AEGIS_LEVERAGES_UNDERL_FUND_HV_DIR_PATH = os.getenv("AEGIS_LEVERAGES_UNDERL_FUND_HV_DIR_PATH")
AEGIS_LEVERAGES_UNDERL_FUND_WR_DIR_PATH = os.getenv("AEGIS_LEVERAGES_UNDERL_FUND_WR_DIR_PATH")

AEGIS_LEVERAGES_UNDERL_FUNDS_DIR_PATHS = {

    os.getenv("AEGIS_DISC_FUND_HV") : AEGIS_LEVERAGES_UNDERL_FUND_HV_DIR_PATH,
    os.getenv("AEGIS_DISC_FUND_WR") : AEGIS_LEVERAGES_UNDERL_FUND_WR_DIR_PATH,

}

AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH = os.getenv("AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH")
AEGIS_LEVERAGES_TRADE_FUND_WR_DIR_PATH = os.getenv("AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH")

AEGIS_LEVERAGES_TRADE_FUNDS_DIR_PATHS = {

    os.getenv("FUND_HV") : AEGIS_LEVERAGES_TRADE_FUND_HV_DIR_PATH,
    os.getenv("FUND_WR") : AEGIS_LEVERAGES_TRADE_FUND_WR_DIR_PATH,

}